# DON'T REMOVE THIS FILE.
# This file is for render site varibles and plugins
#
# The actual configuration files are stored in the `config/_default/` folder.

######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary     = "#001e61"  # Rayados navy blue (primary CTA, highlights)
color_secondary   = "#7a7a7a"  # Cool silver/gray (accents, footers)
light             = "#f2f4f8"  # Very light gray (section background)
black             = "#0a0a0a"  # Almost black (strong contrast)
white             = "#ffffff"  # Clean white
text_dark         = "#1a1a1a"  # Body text (dark grayish)
text_color        = "#4b4b4b"  # Paragraphs, muted content
bg_gray           = "#e6e9ef"  # Light gray for subtle background sections
body_color        = "#ffffff"  # Page background
border_color      = "#d0d4dc"  # Light blue-gray lines (dividers)

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_icon = "themify" # themify icon pack : https://themify.me/themify-icons
font_primary = "Poppins:wght@400;500;600;700" 
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = "Open+Sans:wght@400;500;600;700;800" 
font_secondary_type = "sans-serif" # [serif/sans-serif]

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/themify-icons/icons.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"

# JS Plugins 
# [[params.plugins.js]]
# link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
[[params.plugins.js]]
link = "js/gallery-slider.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "js/tab.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "plugins/filterizr/min.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
